# Generated by Django 3.0.5 on 2021-10-26 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('core', models.CharField(choices=[('EMOTIONAL_HEALTH', 'Emotional Health'), ('RELATIONSHIPS', 'Relationships'), ('CAREER_FINANCES', 'Career & Finances'), ('MINDSET', 'Mindset'), ('PHYSICAL_HEALTH', 'Physical Health')], max_length=50)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corequiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Core quiz',
                'verbose_name_plural': 'Core quizzes',
            },
        ),
    ]
