# Generated by Django 3.0.5 on 2021-09-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockpitlistbase',
            name='sorted_by_type',
            field=models.CharField(choices=[('CORE', 'Core'), ('SORTABLE', 'Sortable')], default='CORE', max_length=25),
        ),
    ]
