# Generated by Django 3.0.5 on 2021-10-22 20:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_auto_20210111_1622'),
        ('cockpit_list', '0002_cockpitlistbase_sorted_by_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cockpitlist',
            old_name='sorted_items',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='cockpitlist',
            name='sorted_by_type',
        ),
        migrations.RemoveField(
            model_name='cockpitlistbase',
            name='sorted_by_type',
        ),
        migrations.AddField(
            model_name='cockpitlist',
            name='category',
            field=models.CharField(choices=[('CORE', 'Core'), ('SORTABLE', 'Sortable'), ('CONFIGURABLE', 'Configurable')], default='CORE', max_length=25),
        ),
        migrations.AddField(
            model_name='cockpitlist',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.Destination'),
        ),
        migrations.AddField(
            model_name='cockpitlist',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
        migrations.AddField(
            model_name='cockpitlistbase',
            name='category',
            field=models.CharField(choices=[('CORE', 'Core'), ('SORTABLE', 'Sortable'), ('CONFIGURABLE', 'Configurable')], default='CORE', max_length=25),
        ),
        migrations.AddField(
            model_name='cockpitlistbase',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.Destination'),
        ),
        migrations.AddField(
            model_name='cockpitlistbase',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
