# Generated by Django 3.0.5 on 2021-11-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cockpit_list', '0003_auto_20211022_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cockpitlist',
            options={'verbose_name': 'User Cockpit list', 'verbose_name_plural': 'User Cockpit lists'},
        ),
    ]
