# Generated by Django 3.0.5 on 2020-11-13 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Self review',
                'verbose_name_plural': 'Self reviews',
            },
        ),
        migrations.CreateModel(
            name='Anwser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('anwser', models.TextField()),
                ('question_number', models.IntegerField()),
                ('self_review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anwsers', to='self_review.SelfReview')),
            ],
            options={
                'verbose_name': 'Anwser',
                'verbose_name_plural': 'Anwsers',
            },
        ),
    ]
