# Generated by Django 3.0.5 on 2020-11-13 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfreview',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
