# Generated by Django 3.0.5 on 2021-01-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_review', '0002_auto_20201113_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('answer', models.TextField()),
                ('question_number', models.IntegerField()),
                ('self_review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='self_review.SelfReview')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.DeleteModel(
            name='Anwser',
        ),
    ]
