# Generated by Django 3.0.5 on 2020-11-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('destination', models.TextField()),
                ('length', models.IntegerField()),
                ('momentum_required', models.IntegerField()),
                ('habits_per_core', models.IntegerField()),
                ('missions_per_journey', models.IntegerField()),
                ('cores', models.IntegerField()),
                ('core_cap', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['length'],
            },
        ),
    ]
