# Generated by Django 3.0.5 on 2021-01-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destinationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='index',
            field=models.IntegerField(default=-1),
        ),
    ]
