# Generated by Django 3.0.5 on 2021-01-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='habits_per_core',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='missions_per_journey',
        ),
    ]
