# Generated by Django 3.0.5 on 2020-12-27 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('score', models.PositiveIntegerField(default=0)),
                ('nightcheck', models.BooleanField(default=False)),
                ('open', models.BooleanField(default=True)),
                ('core', models.CharField(choices=[('EMOTIONAL_HEALTH', 'Emotional Health'), ('RELATIONSHIPS', 'Relationships'), ('CAREER_FINANCES', 'Career & Finances'), ('MINDSET', 'Mindset'), ('PHYSICAL_HEALTH', 'Physical Health')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercheck', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HabitsBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], max_length=50)),
                ('description', models.TextField()),
                ('core', models.CharField(choices=[('EMOTIONAL_HEALTH', 'Emotional Health'), ('RELATIONSHIPS', 'Relationships'), ('CAREER_FINANCES', 'Career & Finances'), ('MINDSET', 'Mindset'), ('PHYSICAL_HEALTH', 'Physical Health')], max_length=50)),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], max_length=50)),
                ('description', models.TextField()),
                ('core', models.CharField(choices=[('EMOTIONAL_HEALTH', 'Emotional Health'), ('RELATIONSHIPS', 'Relationships'), ('CAREER_FINANCES', 'Career & Finances'), ('MINDSET', 'Mindset'), ('PHYSICAL_HEALTH', 'Physical Health')], max_length=50)),
                ('formed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userhabits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyHabits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('dailycheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkdaily', to='habits.DailyCheck')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitdaily', to='habits.Habits')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
