# Generated by Django 3.0.5 on 2021-05-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheck',
            name='morningcheck',
            field=models.BooleanField(default=False),
        ),
    ]
