# Generated by Django 3.0.5 on 2021-08-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_dailycheck_morningcheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habits',
            name='status',
        ),
        migrations.RemoveField(
            model_name='habitsbase',
            name='status',
        ),
    ]
