# Generated by Django 3.0.5 on 2021-08-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_remove_field_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habitsbase',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
