# Generated by Django 3.0.5 on 2021-08-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_add_field_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
