# Generated by Django 3.0.5 on 2021-08-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habits_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habits',
            old_name='status',
            new_name='positive',
        ),
        migrations.RenameField(
            model_name='habitsbase',
            old_name='status',
            new_name='positive',
        ),
    ]
