# Generated by Django 3.0.5 on 2021-11-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_rename_field_status_to_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
