# Generated by Django 3.0.5 on 2021-12-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_habits_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='selected_date',
            field=models.DateField(null=True),
        ),
    ]
