# Generated by Django 3.0.5 on 2022-02-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_habits_selected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheck',
            name='created',
            field=models.DateTimeField(help_text='Date time on which the object was created.', verbose_name='created at'),
        ),
    ]
