# Generated by Django 3.0.5 on 2020-11-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonususer',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
