# Generated by Django 3.0.5 on 2021-01-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0002_bonususer_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonususer',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
