# Generated by Django 3.0.5 on 2021-04-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0003_bonususer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
