# Generated by Django 3.0.5 on 2021-11-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0004_bonus_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
