# Generated by Django 3.0.5 on 2021-11-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0005_alter_field_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonususer',
            name='date_active',
            field=models.DateField(null=True),
        ),
    ]
