# Generated by Django 3.0.5 on 2021-12-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermission',
            name='mission_name',
        ),
        migrations.AddField(
            model_name='usermission',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_missions', to='mission.Mission'),
        ),
    ]
