# Generated by Django 3.0.5 on 2020-11-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mantra',
            field=models.TextField(default=None, null=True),
        ),
    ]
