# Generated by Django 3.0.5 on 2020-11-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_night_check',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='night_checks_in_row',
            field=models.IntegerField(default=0),
        ),
    ]
