# Generated by Django 3.0.5 on 2020-12-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201130_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='core_cap',
            field=models.IntegerField(default=0),
        ),
    ]
