# Generated by Django 3.0.5 on 2020-12-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_core_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='days_in_journey',
            field=models.IntegerField(default=1),
        ),
    ]
