# Generated by Django 3.0.5 on 2020-12-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_days_in_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='core_power_increase',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='core_cap',
            field=models.IntegerField(default=50),
        ),
    ]
