# Generated by Django 3.0.5 on 2020-12-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201218_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='morning_check_time',
            field=models.TimeField(default='09:00:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='night_check_time',
            field=models.TimeField(default='21:00:00', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pause',
            field=models.BooleanField(default=False),
        ),
    ]
