# Generated by Django 3.0.5 on 2020-12-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201222_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='in_journey',
            field=models.BooleanField(default=False),
        ),
    ]
