# Generated by Django 3.0.5 on 2021-01-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_in_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='destination_index',
            field=models.IntegerField(default=0),
        ),
    ]
