# Generated by Django 3.0.5 on 2021-01-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_destination_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='days_in_journey',
            field=models.IntegerField(default=0),
        ),
    ]
