# Generated by Django 3.0.5 on 2021-05-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210111_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='destination_index',
            field=models.IntegerField(default=1),
        ),
    ]
