# Generated by Django 3.0.5 on 2021-06-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210526_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='core_cap',
            field=models.IntegerField(default=0),
        ),
    ]
