# Generated by Django 3.0.5 on 2021-06-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_field_core_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
