# Generated by Django 3.0.5 on 2021-10-04 15:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('topic', models.TextField(blank=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('users', models.ManyToManyField(related_name='user_device_push_notifications', to='users.UserDevice')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
