# Generated by Django 3.0.5 on 2021-10-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_pushnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushnotification',
            options={},
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'QUEUED'), ('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('SENT', 'SENT'), ('FAILED', 'FAILED')], default='PENDING', max_length=50),
        ),
    ]
