# Generated by Django 3.0.5 on 2021-10-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20211004_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotification',
            name='users',
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='user_devices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_notifications', to='users.UserDevice'),
        ),
    ]
