# Generated by Django 3.0.5 on 2021-10-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20211004_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushnotification',
            old_name='user_devices',
            new_name='user_device',
        ),
    ]
