# Generated by Django 3.0.5 on 2021-10-11 19:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20211004_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='request_body',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='request_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
