# Generated by Django 3.0.5 on 2021-10-11 19:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20211011_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('SENT', 'SENT'), ('FAILED', 'FAILED')], default='PENDING', max_length=50)),
                ('request_body', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('request_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('subject', models.TextField()),
                ('to', models.EmailField(max_length=254)),
                ('html_body', models.TextField(blank=True)),
                ('text_body', models.TextField(blank=True)),
                ('context_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
