# Generated by Django 3.0.5 on 2021-10-11 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_emailnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
