# Generated by Django 3.0.5 on 2021-10-17 15:58

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20211011_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tz_zone',
            field=timezone_field.fields.TimeZoneField(default='America/Chicago'),
        ),
    ]
