# Generated by Django 3.0.5 on 2021-10-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_tz_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
