# Generated by Django 3.0.5 on 2021-10-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_pushnotification_delivery_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='set to true when address email have verified'),
        ),
    ]
