# Generated by Django 3.0.5 on 2021-10-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='registration_id',
            field=models.CharField(max_length=255),
        ),
    ]
