# Generated by Django 3.0.5 on 2021-10-28 04:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20211026_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
