# Generated by Django 3.0.5 on 2021-11-16 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_codefile_redemptioncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemptioncode',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
