# Generated by Django 3.0.5 on 2022-03-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_userprofile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
    ]
