# Generated by Django 3.0.5 on 2022-03-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_userprofile_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
    ]
