# Generated by Django 3.0.5 on 2022-04-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_field_notifications_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'QUEUED'), ('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('NOT_SENT', 'NOT_SENT')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'QUEUED'), ('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('NOT_SENT', 'NOT_SENT')], default='PENDING', max_length=50),
        ),
    ]
