# Generated by Django 3.0.5 on 2020-11-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreuser',
            name='core',
        ),
        migrations.AddField(
            model_name='coreuser',
            name='core_string',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Core',
        ),
    ]
