# Generated by Django 3.0.5 on 2020-12-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0002_auto_20201125_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='core_cap',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='power_previous_day',
            field=models.IntegerField(default=0),
        ),
    ]
