# Generated by Django 3.0.5 on 2020-12-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0003_auto_20201218_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreuser',
            name='core_cap',
        ),
    ]
