# Generated by Django 3.0.5 on 2021-11-01 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_auto_20210111_1622'),
        ('improvements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvement',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='improvement',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='destinations.Destination'),
        ),
        migrations.AddField(
            model_name='improvement',
            name='improvement_type',
            field=models.CharField(blank=True, choices=[('ARMOR', 'Armor'), ('WINGS', 'Wings'), ('THRUSTER', 'Thruster')], max_length=55),
        ),
        migrations.AddField(
            model_name='improvement',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='improvementuser',
            name='equipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='improvement',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Amount of credits the item/improvement costs.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='improvement',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='improvement',
            name='probability_reward',
            field=models.IntegerField(default=0, help_text='Chance of item dropping as a reward. 0% for items that cannot drop.'),
        ),
    ]
