# Generated by Django 3.0.5 on 2021-12-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvements', '0002_alter_table_improvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvement',
            name='bonus_core_cap',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='improvement',
            name='core_power_multiplier',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
