# Generated by Django 3.0.5 on 2020-11-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantras',
            options={'verbose_name': 'Mantra', 'verbose_name_plural': 'Mantras'},
        ),
    ]
