# Generated by Django 3.0.5 on 2021-12-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquest',
            name='quest_name',
        ),
        migrations.AddField(
            model_name='userquest',
            name='quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quests', to='quests.Quest'),
        ),
    ]
