# Generated by Django 3.0.5 on 2020-11-24 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destinations', '0002_destinationuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.TextField()),
                ('quantity_days', models.IntegerField(default=0)),
                ('quantity_momentum', models.IntegerField(default=0)),
                ('quantity_habits', models.IntegerField(default=0)),
                ('reach_destination', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trophy_related', to='destinations.Destination')),
            ],
            options={
                'verbose_name': 'Trophy',
                'verbose_name_plural': 'Trophies',
            },
        ),
        migrations.CreateModel(
            name='TrophyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('trophy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='trophy.Trophy')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
