# Generated by Django 3.0.5 on 2022-03-21 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_auto_20210111_1622'),
        ('trophy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophy',
            name='reach_destination',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trophy_related', to='destinations.Destination'),
        ),
    ]
